### ISSUE TITLE
Invalid commands in vifmrc

### ISSUE THREAD

**Issue by xaizek** [benelan/dotfiles#1]
Hi,

This portion of your config was referenced on [Vifm Q&A](https://q2a.vifm.info/1604/various-feedback):

https://github.com/benelan/dotfiles/blob/022313d945ab355609108d8d56462b9019d11aaa/.config/vifm/vifmrc#L129-L134

It doesn't work and should look like:

    execute 'mark d' fnameescape($DOTFILES)
    " etc.

**Comment by benelan** [comment]
Hmm very weird, it has always worked for me. I just tested and confirmed - I can press `'d` and it will jump to `~/.dotfiles`. Maybe it has something to do with the way you set the environment variables? Here are mine:

https://github.com/benelan/dotfiles/blob/318634efcf36ea9c58966e52ecf8f31b23d8a2a3/.dotfiles/shell/exports.sh#L10-L16

Sorry for the belated reply, I didn't see this until now. I love Vifm, thanks for all your hard work!

**Comment by xaizek** [comment]
I guess you used different commands initially and marks got cached in `vifminfo` file.  If you try running Vifm like `DOTFILES=abcd vifm`, <kbd>'d</kbd> will probably still work and `:marks d` will still show something like `/home/benelan/.dotfiles`.

**Comment by benelan** [comment]
>  If you try running Vifm like DOTFILES=abcd vifm, 'd will probably still work and :marks d will still show something like /home/benelan/.dotfiles.

Yup you were right! Thanks for letting me know and providing a solution
